#
# // SPDX-FileCopyrightText: 2026 Istituto Nazionale di Fisica Nucleare
# //
# // SPDX-License-Identifier: EUPL-1.2
#

spring:
  devtools:
    livereload:
      enabled: false
x509:
  trustAnchorsDir: ${X509_TRUST_ANCHORS_DIR:/etc/grid-security/certificates}