x509:
  trustAnchorsDir: ${X509_TRUST_ANCHORS_DIR:/tmp}

oidc:
  clients:
      - issuer-url: http://localhost:8080/
        client-id: password-grant
        client-secret: secret
      - issuer-url: https://iam.local.io/
        client-id: argus-oidc-client-id
        client-secret: argus-oidc-client-secret
